backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: static/img
public_folder: /img
media_library:
  name: uploadcare
  config:
    publicKey: 34dbd396fc0bbf023e54
collections:
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Info/About"
        name: "about"
        file: "content/pages/info.md"
        fields:
          - {label: 'Title (internal)', name: 'title', widget: 'string'}
          - {label: 'About', name: 'about', widget: 'markdown'}
          - {label: 'Profiles', name: 'profiles', widget: 'markdown'}
          - {label: 'Contact', name: 'contact', widget: 'markdown'}
          - {label: 'Locations', name: 'location', widget: 'markdown'}
      - label: "Homepage"
        name: "home"
        file: "content/pages/homepage.md"
        fields:
          - {label: 'Title (internal)', name: 'title', widget: 'string'}
          - {label: 'Intro', name: 'intro', widget: 'markdown'}
          - { label: 'Featured Projects', name: 'projects', widget: 'list', 
              fields: [ { label: "Project", name: "project", widget: "relation", collection: "projects", search_fields: ["title"], value_field: "title", display_fields: ["campaign_title"]}]
              }
          - { label: 'Selected Clients', name: 'clients', widget: 'list', 
              fields: [ { label: "Client", name: "client", widget: "relation", collection: "clients", search_fields: ["name"], value_field: "name", display_fields: ["name"]}]
              }
          - { label: 'Selected Artists', name: 'artists', widget: 'list', 
              fields: [ { label: "Artist", name: "artist", widget: "relation", collection: "artists", search_fields: ["name"], value_field: "name", display_fields: ["name"]}]
              }
      - label: "Cookie Policy"
        name: "cookie"
        file: "content/pages/cookie.md"
        fields:
          - {label: 'Title (internal)', name: 'title', widget: 'string'}
          - {label: 'Cookie Policy', name: 'cookie', widget: 'markdown'}
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'projects'
    label: 'Project'
    folder: 'content/projects'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title (internal)', name: 'title', widget: 'string' }
      - { label: 'Description (internal)', name: 'description', widget: 'string',required: false }
      - { label: 'Campaign Title', name: 'campaign_title', widget: 'markdown' }
      - { label: 'Thumbnail', name: 'thumb', widget: 'object', fields: [{ label: 'Alt Text (for screen readers)', name: 'media_name', widget: 'string',required: false },{ label: 'Aspect Ratio', name: 'size', widget: 'select', options: ["portrait", "landscape", "square"], required: true }, { label: 'Image (or fallback image for video)', name: 'image', widget: 'image', required: false, preview: true}, { label: 'Video', name: 'video', widget: 'file', required: false, preview: true}] }
      - { label: 'Release Date Internal', name: 'release_date', widget: 'datetime' }
      - { label: 'Release Date External', name: 'release_date_public', widget: 'markdown' }
      - { label: 'Notes', name: 'notes', widget: 'markdown',required: false }
      - { label: 'Media', name: 'media', widget: 'list', 
          fields: [{ label: 'Alt Text (for screen readers)', name: 'media_name', widget: 'string', required: false },{ label: 'Aspect Ratio', name: 'size', widget: 'select', options: ["portrait", "landscape", "square"], required: true },{ label: "Image (or backup image for video)", name: "media", widget: 'image',required: false, preview: true},{ label: "Video", name: "mediaVideo",required: false, widget: 'file',preview: true}]
        }
      - { label: 'Clients', name: 'clients', widget: 'list', 
        fields: [ { label: "Client", name: "client", widget: "relation", collection: "clients", search_fields: ["name"], value_field: "name", display_fields: ["name"]}]
        }
      - { label: 'Artists', name: 'artists', widget: 'list', 
        fields: [ { label: "Artist", name: "artist", widget: "relation", collection: "artists", search_fields: ["name"], value_field: "name", display_fields: ["name"]}]
        }
      - { label: 'Categories', name: 'categories', widget: 'list', 
        fields: [ { label: "Category", name: "category", widget: "relation", collection: "categories", search_fields: ["name"], value_field: "name", display_fields: ["name"]}]
        }
      - { label: 'Locations', name: 'locations', widget: 'list', 
        fields: [ { label: "Location", name: "location", widget: "relation", collection: "locations", search_fields: ["name"], value_field: "name", display_fields: ["name"]}]
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  - name: 'clients'
    label: 'Client'
    folder: 'content/clients'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title (internal)', name: 'title', widget: 'string' }
      - { label: 'Name', name: 'name', widget: 'markdown' }
  - name: 'artists'
    label: 'Artist'
    folder: 'content/artists'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title (internal)', name: 'title', widget: 'string' }
      - { label: 'Name', name: 'name', widget: 'markdown' }
  - name: 'locations'
    label: 'Location'
    folder: 'content/locations'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title (internal)', name: 'title', widget: 'string' }
      - { label: 'Name', name: 'name', widget: 'markdown' }
      - { label: 'Address', name: 'address', widget: 'markdown', required: false }
      - { label: 'Latitude (use negative for North)', name: 'latitude', widget: 'string', required: false }
      - { label: 'Longitude (use negative for West)', name: 'longitude', widget: 'string', required: false }
  - name: 'categories'
    label: 'Category'
    folder: 'content/categories'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title (internal)', name: 'title', widget: 'string' }
      - { label: 'Name', name: 'name', widget: 'markdown' }
      - { label: 'Description (internal)', name: 'description', widget: 'markdown', required: false }